apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app:  rabbitmq
    project:  roboshop
    tier: db
spec: 
  selector:
    matchLabels:
      app:  rabbitmq
      project:  roboshop
      tier: db
  serviceName:  "rabbitmq"
  replicas: {{  .Values.statefulset.replicas }}
  minReadySeconds:  10
  template:
    metadata:
      labels:
        app:  rabbitmq
        project:  roboshop
        tier: db
    spec: 
      containers:
      - name: rabbitmq
        image:  rabbitmq
        envFrom:
        - secretRef:
            name: rabbitmq
        volumeMounts:
        - name: rabbitmq
          mountPath:  /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes:  [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc" #provide storage class name after creaing it
      resources:
        requests:
          storage:  2Gi

