pipeline {
    agent {
        node{
            label 'AGENT-1'
        }
    }
    environment {
        GREETING = 'Hello Jenkins'
    }
    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds() }

    stages {
        stage('Hello') {
            steps {
                echo "Hello User"
            }
        }
        stage('Earth'){
            steps{
                echo "Earth is Round"
            }
        }
        stage('Good Morning'){
            steps{
                sh """
                echo "$GREETING"
                sleep 10
                """
            }
        }
    }
    post {
        always {
            echo "Pipeline execution completed"
        }
        failure {
            echo "Pipeline Fialed"
        }
        success{
            echo "Pipeline Success"
        }
    }
}