pipeline {
    agent {
        node{
            label 'AGENT-1'
        }
    }

    stages {
        stage('Hello') {
            steps {
                echo "Hello"
            }
        }
        stage('Earth'){
            steps{
                echo "Earth"
            }
        }
        stage('Good Morning'){
            steps{
                echo "Good Morning"
            }
        }
    }
}