- name: conditions
  hosts:  localhost
  become: yes
  tasks:
  - name: Check Username Existence
    ansible.builtin.command: id roboshop
    register: userES
    ignore_errors: true
  - name: print value
    ansible.builtin.debug:
      msg:  "output is {{userES}}"
  - name: print exit status
    ansible.builtin.debug:
      msg:  "ES is {{userES.rc}}"
  - name: Creating User
    ansible.builtin.user: 
      name: roboshop
    when: userES.rc != 0 #condition