- name: Loops
  hosts:  localhost
  tasks:  
  - name: print names
    ansible.builtin.debug:
      msg:  "name is {{item}}" #item is used to iterate through loop and cant be changed
    loop:  #loops
    - BALAJI
    - GOPI
    - ALEHKYA
    - DEEPAK
    - PAVAN


    #names can be replaced with packages to install all packages

- name: Installing and Uninstalling Packages Using LOOPS
  hosts:  localhost
  tasks:
  - name: Installing and Uninstalling Packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
      #state: absent
    loop:
    - {name:  'git',state:  'present'}
    - {name:  'nginx',state:  'present'}
    - {name:  'postfix',state:  'absent'}
    - {name:  'mysql',state:  'absent'}
