apiVersion: app/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app:  redis
    project:  roboshop
    tier: db
spec: 
  selector:
    matchLabels:
      app:  redis
      project:  roboshop
      tier: db
  serviceName:  "redis"
  replicas: {{  .Values.stateful-set.replicas }}
  minReadySeconds:  10
  template:
    metadata:
      labels:
        app:  redis
        project:  roboshop
        tier: db
    spec: 
      containers:
      - name: redis
        image:  redis
        volumeMounts:
        - name: redis
          mountPath:  /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes:  [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc" #provide storage class name after creaing it
      resources:
        requests:
          storage:  1Gi

